import { INodePopulator } from "./WorldGenerator2";

export const BuiltinPopulators: Array<INodePopulator> = [
    {
        id: "artifact.sculpture",
        populatorType: "item",
        name: [
            "Beautiful Stone Sculpture",
            "Exquisite Marvel Sculpture",
            "Nice Bronze Sculpture",
        ],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.map",
        populatorType: "item",
        name: ["Map of Land", "Map of the World"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.letter",
        populatorType: "item",
        name: "Handwritten Letter",
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.book",
        populatorType: "item",
        name: ["Book on History", "Book on Magic", "Book on Science"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.painting",
        populatorType: "item",
        name: ["Beautiful Painting", "Exquisite Painting", "Nice Painting"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.religious-icon",
        populatorType: "item",
        name: ["Religious Icon", "Holy Icon", "Sacred Icon"],
        tier: ["common"],
        type: "artifact",
    },
    {
        id: "artifact.religious-book",
        populatorType: "item",
        name: ["Religious Book", "Religious Singing Book", "Sacred Book"],
        tier: ["common"],
        type: "artifact",
    },
    {
        id: "building.alchemists-guild",
        populatorType: "children",
        name: "Alchemist's Guild",
        distance: 5,
        humidity: ["normal", "dry"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "store" },
        labels: ["alchemists-guild"],
    },
    {
        id: "wearable.rare.nice-amulet",
        populatorType: "item",
        name: ["Nice Amulet", "Amulet of Protection", "Silver Amulet"],
        tier: "rare",
        type: "wearable",
        wearable: {
            wearableType: "necklace",
            defense: { min: 10, max: 20 },
            effects: [
                {
                    name: "minor-heal",
                    type: "heal",
                    activation: "when-defending",
                    value: 20,
                },
            ],
        },
    },
    {
        id: "item.alchemists-guild.alchemist.loot",
        populatorType: "item",
        oneOf: [
            "consumable.healing-potion.small",
            "consumable.healing-potion.normal",
            "consumable.healing-potion.large",
            "consumable.poison.small",
            "consumable.poison.normal",
            "material.herb",
            "material.potion-ingredient",
        ],
        probability: 1,
        lootable: true,
    },
    {
        id: "npc.alchemists-guild.alchemist",
        populatorType: "npc",
        name: "Alchemist",
        health: { status: "healthy", points: 1200, max: 1200 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            boots: "boots.rare.nice-boots",
            helmet: "helmet.rare.nice-helmet",
            wearable: "wearable.rare.nice-amulet",
            weapon: "weapon.rare.nice-staff",
        },
        personality: {
            traits: ["curious", "diligent", "patient", "optimistic", "humble"],
            background: "alchemist",
        },
        inventory: {
            gold: [500, 1000, 2000, 3000],
            items: [
                "item.alchemists-guild.alchemist.loot",
                "item.alchemists-guild.alchemist.loot",
                "item.alchemists-guild.alchemist.loot",
                "item.alchemists-guild.alchemist.loot",
                "item.alchemists-guild.alchemist.loot",
            ],
        },
    },
    {
        id: "populators.builtin.common-armor.simple-armor",
        populatorType: "item",
        name: ["Simple Chestplate", "Simple Armor", "Simple Leather Armor"],
        tier: "common",
        type: "armor",
        armor: { defense: { min: 2, max: 10 } },
    },
    {
        id: "armor.common.simple-clothing",
        populatorType: "item",
        name: ["Simple Clothing", "Simple Garment", "Simple Outfit"],
        tier: "common",
        type: "armor",
        armor: { defense: { min: 0, max: 3 } },
    },
    {
        id: "armor.rare.elegant-clothing",
        populatorType: "item",
        name: ["Elegant Clothing", "Noble Elegant Garment", "Elegant Outfit"],
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 25, max: 50 } },
    },
    {
        id: "armor.rare.nice-armor",
        populatorType: "item",
        name: ["Nice Steel Armor", "Nice Iron Armor"],
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 30, max: 150 } },
    },
    {
        id: "armor.rare.priest-robe",
        populatorType: "item",
        name: "Black Robe of Priest",
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 1, max: 5 } },
    },
    {
        id: "armor.animal.wolf-fur",
        populatorType: "item",
        name: "Wolf Fur",
        tier: "common",
        type: "armor",
        armor: { defense: { min: 10, max: 13 } },
        lootable: false,
    },
    {
        id: "armor.common.simple-chainmail",
        populatorType: "item",
        name: ["Simple Chainmail", "Chainmail Armor", "Simple Chainmail Armor"],
        tier: "common",
        type: "armor",
        armor: { defense: { min: 5, max: 15 } },
    },
    {
        id: "building.blacksmith",
        populatorType: "children",
        name: "Blacksmith Workshop",
        distance: 5,
        humidity: "dry",
        temperature: ["warm", "hot"],
        type: "building",
        building: { buildingType: "store" },
        labels: ["blacksmith"],
    },
    {
        id: "item.blacksmith.smith.loot",
        populatorType: "item",
        oneOf: [
            "weapon.rare.nice-sword",
            "weapon.rare.nice-axe",
            "armor.rare.nice-armor",
        ],
        lootable: true,
    },
    {
        id: "npc.blacksmith.smith",
        populatorType: "npc",
        name: "Smith",
        health: { status: "healthy", points: 2000, max: 2000 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.rare.elegant-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: ["weapon.rare.nice-sword", "weapon.rare.nice-axe"],
            },
        },
        inventory: {
            gold: [4000, 10000],
            items: [
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
                "item.blacksmith.smith.loot",
            ],
        },
        personality: {
            traits: [
                "cautious",
                "indifferent",
                "disciplined",
                "patient",
                "honest",
            ],
            background: "blacksmith",
        },
    },
    {
        id: "boots.common.simple-boots",
        populatorType: "item",
        name: ["Simple Boots", "Simple Footwear", "Simple Shoes"],
        tier: "common",
        type: "boots",
        boots: { defense: { min: 0, max: 3 } },
    },
    {
        id: "boots.rare.elegant-boots",
        populatorType: "item",
        name: ["Elegant Boots", "Noble Elegant Footwear", "Elegant Shoes"],
        tier: "rare",
        type: "boots",
        boots: { defense: { min: 20, max: 50 } },
    },
    {
        id: "boots.rare.nice-boots",
        populatorType: "item",
        name: ["Nice Steel Boots", "Polished Iron Boots", "Nice Boots"],
        tier: "rare",
        type: "boots",
        boots: { defense: { min: 30, max: 60 } },
    },
    {
        id: "wilderness.cave",
        populatorType: "children",
        name: "Cave",
        distance: 15,
        humidity: ["normal", "humid", "wet"],
        temperature: ["cool", "cold"],
        type: "wilderness",
        wilderness: { wildernessType: "cave" },
        labels: ["cave"],
    },
    {
        id: "material.cave.stone",
        populatorType: "item",
        name: [
            "Stone",
            "Rock",
            "Rough Stone",
            "Cave Stone",
            "Crystalline Rock",
        ],
        tier: "common",
        type: "material",
        labels: ["stone", "cave-material"],
        probability: 0.8,
    },
    {
        id: "material.cave.ore",
        populatorType: "item",
        name: ["Ore", "Iron Ore", "Copper Ore", "Cave Ore", "Rare Ore"],
        tier: ["common", "rare"],
        type: "material",
        labels: ["ore", "cave-material"],
        probability: 0.3,
    },
    {
        id: "npc.cave.giant-spider",
        populatorType: "npc",
        name: "Giant Spider",
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 1500, max: 1500 },
        gear: { weapon: "weapon.animal.spider-fangs" },
        labels: ["spider"],
    },
    {
        id: "npc.church.priest",
        populatorType: "npc",
        name: "Priest",
        health: { status: "healthy", points: 100, max: 100 },
        race: "human",
        stance: "friendly",
        gear: { armor: "armor.rare.priest-robe" },
        personality: {
            traits: ["kind", "patient", "loyal", "forgiving", "compassionate"],
            background: "priest",
        },
        inventory: {
            gold: [0, 10, 25, 50, 100],
            items: [{ oneOf: ["artifact.religious-book"] }],
        },
    },
    {
        id: "building.church",
        populatorType: "children",
        name: "Church",
        distance: 5,
        humidity: ["dry", "normal"],
        temperature: ["mild", "cool", "cold"],
        type: "building",
        building: { buildingType: "church" },
        labels: ["church"],
    },
    {
        id: "wilderness.desert",
        populatorType: "children",
        name: "Desert",
        distance: 40,
        humidity: "dry",
        temperature: "scorching",
        type: "wilderness",
        wilderness: { wildernessType: "desert" },
    },
    {
        id: "npc.desert.scorpion.venom",
        populatorType: "npc",
        name: "Scorpion",
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 50, max: 50 },
        gear: {
            weapon: {
                id: "weapon.animal.scorpion-venom-claws",
                populatorType: "item",
                name: "Scorpion Venom Claws",
                tier: "common",
                type: "weapon",
                weapon: { weaponType: "knife", damage: { min: 75, max: 100 } },
                noAi: true,
                lootable: false,
            },
        },
    },
    {
        id: "npc.desert.scorpion",
        populatorType: "npc",
        name: "Scorpion",
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 50, max: 50 },
        gear: { weapon: "weapon.animal.scorpion-venom-claws" },
    },
    {
        id: "consumable.healing-potion.small",
        populatorType: "item",
        name: ["Small Healing Potion", "Tiny Potion of Healing"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [10, 25] }],
        },
    },
    {
        id: "consumable.healing-potion.normal",
        populatorType: "item",
        name: ["Healing Potion", "Potion of Healing"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [100, 150] }],
        },
    },
    {
        id: "consumable.healing-potion.large",
        populatorType: "item",
        name: ["Large Healing Potion", "Big Potion of Healing"],
        tier: "epic",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [500, 750] }],
        },
    },
    {
        id: "consumable.poison.small",
        populatorType: "item",
        name: ["Small Vile of Poison", "Poison Vile"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Poison Yourself",
                    type: "damage-self",
                    value: [10, 25],
                },
            ],
        },
    },
    {
        id: "consumable.poison.normal",
        populatorType: "item",
        name: ["Vile of Poison", "Glass of Poison"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Poison Yourself",
                    type: "damage-self",
                    value: [100, 150],
                },
            ],
        },
    },
    {
        id: "consumable.dynamite",
        populatorType: "item",
        name: "Dynamite Stick",
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Explode Enemy",
                    type: "damage-enemy",
                    value: [100, 150],
                },
            ],
        },
    },
    {
        id: "consumable.scroll.fireball",
        populatorType: "item",
        name: "Scroll of Fireball",
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                { name: "Fireball", type: "damage-enemy", value: [100, 200] },
            ],
        },
        probability: 0.3,
    },
    {
        id: "consumable.scroll.lightning",
        populatorType: "item",
        name: "Scroll of Lightning Bolt",
        tier: "epic",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Lightning Bolt",
                    type: "damage-enemy",
                    value: [250, 500],
                },
            ],
        },
        probability: 0.1,
    },
    {
        id: "building.dungeon",
        populatorType: "children",
        name: "Dungeon",
        distance: 10,
        humidity: ["normal", "humid", "wet"],
        temperature: ["cool", "cold"],
        type: "building",
        building: { buildingType: "dungeon" },
        labels: ["dungeon"],
    },
    {
        id: "item.dungeon.epic.loot",
        populatorType: "item",
        oneOf: [
            "weapon.epic.amazing-sword",
            "weapon.epic.amazing-axe",
            "weapon.epic.amazing-knife",
            "weapon.epic.amazing-dagger",
            "weapon.epic.amazing-bow",
            "weapon.epic.amazing-crossbow",
            "weapon.epic.amazing-staff",
            "armor.rare.nice-armor",
            "helmet.rare.nice-helmet",
            "boots.rare.nice-boots",
            "wearable.rare.nice-amulet",
            "consumable.healing-potion.large",
            "consumable.scroll.lightning",
        ],
        lootable: true,
    },
    {
        id: "item.dungeon.rare.loot",
        populatorType: "item",
        oneOf: [
            "weapon.rare.nice-sword",
            "weapon.rare.nice-axe",
            "weapon.rare.nice-bow",
            "weapon.rare.nice-crossbow",
            "weapon.rare.nice-staff",
            "armor.rare.nice-armor",
            "helmet.rare.nice-helmet",
            "boots.rare.nice-boots",
            "wearable.rare.nice-amulet",
            "consumable.healing-potion.normal",
            "consumable.scroll.fireball",
            "consumable.dynamite",
        ],
        lootable: true,
    },
    {
        id: "item.dungeon.skeleton.loot",
        populatorType: "item",
        oneOf: [
            "weapon.common.simple-sword",
            "armor.common.simple-chainmail",
            "helmet.common.simple-helmet",
            "boots.common.simple-boots",
        ],
        lootable: true,
    },
    {
        id: "npc.dungeon.undead",
        populatorType: "npc",
        name: ["Undead", "Zombie", "Skeleton"],
        race: "animal",
        stance: "hostile",
        health: {
            status: ["healthy", "injured"],
            points: [100, 200, 300],
            max: 300,
        },
        inventory: {
            items: [
                "item.dungeon.skeleton.loot",
                "item.dungeon.skeleton.loot",
                "item.dungeon.skeleton.loot",
            ],
        },
    },
    {
        id: "drink.simple-drink",
        populatorType: "item",
        name: [
            "Drinkable Liquid",
            "Cup of Refresher",
            "Tasty Beverage",
            "Simple Drink",
        ],
        tier: "common",
        type: "drink",
    },
    {
        id: "building.engineers-guild",
        populatorType: "children",
        name: "Engineer's Guild",
        distance: 5,
        humidity: ["normal", "dry"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "store" },
        labels: ["engineers-guild"],
    },
    {
        id: "item.engineers-guild.engineer.loot",
        populatorType: "item",
        oneOf: [
            "material.common",
            "material.iron",
            "material.steel",
            "material.wood",
            "consumable.dynamite",
        ],
        probability: 1,
        lootable: true,
    },
    {
        id: "npc.engineers-guild.engineer",
        populatorType: "npc",
        name: "Engineer",
        health: { status: "healthy", points: 1500, max: 1500 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            boots: "boots.rare.nice-boots",
            helmet: "helmet.rare.nice-helmet",
            weapon: "weapon.rare.nice-staff",
        },
        personality: {
            traits: ["curious", "diligent", "patient", "optimistic", "humble"],
            background: "artisan",
        },
        inventory: {
            gold: [500, 1000, 2000, 3000],
            items: [
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
                "item.engineers-guild.engineer.loot",
            ],
        },
    },
    {
        id: "building.farm",
        populatorType: "children",
        name: "Farm",
        distance: 5,
        humidity: ["normal", "humid"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "farm" },
    },
    {
        id: "room.farm.granary",
        populatorType: "children",
        name: "Granary",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "food.simple-food",
        populatorType: "item",
        name: ["Edible Food", "Tasty Snack", "Healthy Food", "Simple Meal"],
        tier: "common",
        type: "food",
    },
    {
        id: "wilderness.forest",
        populatorType: "children",
        name: "Forest",
        distance: 20,
        humidity: ["normal", "humid", "wet"],
        temperature: ["mild", "cool", "cold"],
        type: "wilderness",
        wilderness: { wildernessType: "forest" },
    },
    {
        id: "npc.forest.wolf",
        populatorType: "npc",
        name: ["Wolf", "Common Wolf", "Forest Wolf"],
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 250, max: 250 },
        gear: {
            weapon: "weapon.animal.wolf-paws",
            armor: "armor.animal.wolf-fur",
        },
    },
    {
        id: "helmet.common.simple-helmet",
        populatorType: "item",
        name: ["Simple Helmet", "Simple Headgear", "Simple Hat"],
        tier: "common",
        type: "helmet",
        helmet: { defense: { min: 0, max: 3 } },
    },
    {
        id: "helmet.rare.elegant-helmet",
        populatorType: "item",
        name: ["Elegant Headwear", "Noble Elegant Hat"],
        tier: "rare",
        type: "helmet",
        helmet: { defense: { min: 10, max: 20 } },
    },
    {
        id: "helmet.rare.nice-helmet",
        populatorType: "item",
        name: ["Nice Steel Helmet", "Polished Iron Helmet"],
        tier: "rare",
        type: "helmet",
        helmet: { defense: { min: 20, max: 30 } },
    },
    {
        id: "room.house.bedroom",
        populatorType: "children",
        name: "Bedroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "bedroom" },
    },
    {
        id: "room.house.kitchen",
        populatorType: "children",
        name: "Kitchen",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "kitchen" },
    },
    {
        id: "room.house.storage",
        populatorType: "children",
        name: "Storeroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "building.house",
        populatorType: "children",
        name: "House",
        distance: 5,
        humidity: ["dry", "normal", "humid"],
        temperature: ["cool", "mild", "warm", "hot"],
        type: "building",
        building: { buildingType: "house" },
        labels: ["house"],
    },
    {
        id: "household.common-item",
        populatorType: "item",
        name: ["Household Item", "Household Tool"],
        tier: "common",
        type: "household",
    },
    {
        id: "household.kitchen-item",
        populatorType: "item",
        name: [
            "Kitchen Tool",
            "Kitchen Container",
            "Kitchen Equipment",
            "Kitchen Utensil",
        ],
        tier: "common",
        type: "household",
    },
    {
        id: "furniture.bed",
        populatorType: "item",
        name: "Bed",
        tier: "common",
        type: "household",
        static: true,
    },
    {
        id: "furniture.chest",
        populatorType: "item",
        name: ["Chest", "Locker", "Box"],
        tier: "common",
        type: "household",
        static: true,
        contains: [
            {
                probability: 0.8,
                name: "Common Household Tool",
                tier: "common",
                type: "household",
            },
            {
                probability: 0.25,
                name: "Rare Household Tool",
                tier: "rare",
                type: "household",
            },
        ],
    },
    {
        id: "household.religious-item",
        populatorType: "item",
        name: ["Religious Item", "Faith Item", "Sacred Item"],
        tier: ["common", "rare"],
        type: "household",
    },
    {
        id: "household.potion-brewing-equipment",
        populatorType: "item",
        name: [
            "Potion Brewing Equipment",
            "Alchemy Set",
            "Brewing Apparatus",
            "Cauldron",
            "Distillation Kit",
        ],
        tier: ["common", "rare"],
        type: "household",
    },
    {
        id: "material.wood",
        populatorType: "item",
        name: [
            "Wood",
            "Lumber",
            "Timber",
            "Wooden Material",
            "Small Wooden Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.stone",
        populatorType: "item",
        name: ["Stone", "Rock", "Pebble", "Small Stone", "Small Rock"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.iron",
        populatorType: "item",
        name: ["Iron", "Iron Ingot", "Iron Material", "Small Iron Material"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.copper",
        populatorType: "item",
        name: [
            "Copper",
            "Copper Ingot",
            "Copper Material",
            "Small Copper Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.steel",
        populatorType: "item",
        name: [
            "Steel",
            "Steel Ingot",
            "Steel Material",
            "Small Steel Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.common",
        populatorType: "item",
        name: [
            "Common Material",
            "Common Resource",
            "Some Material",
            "Some Resource",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.food-ingredient",
        populatorType: "item",
        name: [
            "Spice",
            "Raw Meat",
            "Raw Vegetable",
            "Raw Fruit",
            "Raw Grain",
            "Mushroom",
            "Fish",
            "Food Ingredient",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.drink-ingredient",
        populatorType: "item",
        name: ["Water", "Milk", "Juice", "Drink Ingredient"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.trade-commodity",
        populatorType: "item",
        name: [
            "Trade Commodity",
            "Trade Good",
            "Trade Material",
            "Trade Resource",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "material.herb",
        populatorType: "item",
        name: [
            "Herb",
            "Medicinal Herb",
            "Healing Herb",
            "Rare Herb",
            "Common Herb",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "material.potion-ingredient",
        populatorType: "item",
        name: [
            "Potion Ingredient",
            "Brewing Ingredient",
            "Alchemical Ingredient",
            "Magical Ingredient",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "material.ore",
        populatorType: "item",
        name: ["Ore", "Iron Ore", "Copper Ore", "Gold Ore", "Silver Ore"],
        tier: "common",
        type: "material",
        labels: ["ore"],
    },
    {
        id: "material.crude-rock",
        populatorType: "item",
        name: ["Crude Rock", "Rough Stone", "Unrefined Rock", "Stone", "Rock"],
        tier: "common",
        type: "material",
        labels: ["crude-rock"],
    },
    {
        id: "household.mining-equipment",
        populatorType: "item",
        name: [
            "Mining Pickaxe",
            "Mining Shovel",
            "Mining Cart",
            "Mining Lantern",
            "Mining Helmet",
        ],
        tier: "common",
        type: "household",
        labels: ["mining-equipment"],
    },
    {
        id: "material.sand",
        populatorType: "item",
        name: ["Sand", "Fine Sand", "Coarse Sand", "Desert Sand"],
        tier: "common",
        type: "material",
        labels: ["sand"],
    },
    {
        id: "npc.merchant",
        populatorType: "npc",
        name: "Merchant",
        health: { status: "healthy", points: [150, 200, 300], max: 300 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [500, 700, 1200],
            items: [
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
            ],
        },
        personality: {
            traits: [
                "adventurous",
                "brave",
                "diligent",
                "disciplined",
                "optimistic",
            ],
            background: "merchant",
        },
    },
    {
        id: "building.mine",
        populatorType: "children",
        name: "Mine",
        distance: 10,
        humidity: ["normal", "humid", "wet"],
        temperature: ["cool", "cold"],
        type: "building",
        building: { buildingType: "base" },
        labels: ["mine"],
    },
    {
        id: "npc.mine.miner",
        populatorType: "npc",
        name: "Miner",
        race: "human",
        stance: "friendly",
        health: { status: "healthy", points: 1500, max: 1500 },
        inventory: {
            gold: [100, 200, 300, 500],
            items: [
                { oneOf: ["material.ore", "material.crude-rock"] },
                { oneOf: ["material.ore", "material.crude-rock"] },
                { oneOf: ["material.ore", "material.crude-rock"] },
                { oneOf: ["material.ore", "material.crude-rock"] },
            ],
        },
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: "weapon.common.simple-axe",
        },
        personality: {
            traits: ["diligent", "patient", "honest", "humble"],
            background: "miner",
        },
    },
    {
        id: "wilderness.mountain",
        populatorType: "children",
        name: "Mountain",
        distance: 50,
        humidity: ["normal", "dry"],
        temperature: ["cool", "cold", "freezing"],
        type: "wilderness",
        wilderness: { wildernessType: "mountain" },
    },
    {
        id: "npc.mountain.wolf",
        populatorType: "npc",
        name: ["Wolf", "Common Wolf", "Mountain Wolf"],
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 750, max: 750 },
        gear: {
            weapon: "weapon.animal.wolf-paws",
            armor: "armor.animal.wolf-fur",
        },
    },
    {
        id: "building.pharmacy",
        populatorType: "children",
        name: "Pharmacy",
        distance: 5,
        humidity: ["normal"],
        temperature: ["mild", "cool"],
        type: "building",
        building: { buildingType: "store" },
        labels: ["pharmacy"],
    },
    {
        id: "npc.pharmacy.pharmacist",
        populatorType: "npc",
        name: "Pharmacist",
        health: { status: "healthy", points: 100, max: 100 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            helmet: "helmet.rare.nice-helmet",
            boots: "boots.rare.nice-boots",
            weapon: "weapon.rare.nice-staff",
        },
        personality: {
            traits: [
                "kind",
                "honest",
                "generous",
                "patient",
                "humble",
                "empathetic",
            ],
            background: "healer",
        },
        inventory: {
            gold: [500, 1000, 1500, 2000, 3000],
            items: [
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                { oneOf: ["material.herb", "material.potion-ingredient"] },
                { oneOf: ["material.herb", "material.potion-ingredient"] },
            ],
        },
    },
    {
        id: "wilderness.river",
        populatorType: "children",
        name: "River",
        distance: 30,
        humidity: ["normal", "humid", "wet"],
        temperature: ["mild", "warm", "cool"],
        type: "wilderness",
        wilderness: { wildernessType: "river" },
    },
    {
        id: "npc.river.fish",
        populatorType: "npc",
        name: "Fish",
        race: "animal",
        stance: "neutral",
        health: { status: "healthy", points: 50, max: 50 },
        labels: ["fish"],
    },
    {
        id: "wilderness.swamp",
        populatorType: "children",
        name: "Swamp",
        distance: 25,
        humidity: ["humid", "wet"],
        temperature: ["mild", "warm"],
        type: "wilderness",
        wilderness: { wildernessType: "swamp" },
        labels: ["swamp"],
    },
    {
        id: "npc.swamp.swamp-monster",
        populatorType: "npc",
        name: "Swamp Monster",
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 1000, max: 1000 },
        gear: {
            weapon: "weapon.animal.swamp-monster-claws",
            armor: "armor.animal.swamp-monster-skin",
        },
        labels: ["swamp-monster"],
    },
    {
        id: "npc.swamp.alligator",
        populatorType: "npc",
        name: "Alligator",
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 500, max: 500 },
        gear: { weapon: "weapon.animal.alligator-teeth" },
        labels: ["alligator"],
    },
    {
        id: "npc.swamp.bog-witch",
        populatorType: "npc",
        name: "Bog Witch",
        race: "human",
        stance: ["neutral", "hostile"],
        health: { status: "healthy", points: 750, max: 750 },
        gear: {
            weapon: "weapon.rare.nice-staff",
            wearable: "wearable.rare.nice-amulet",
        },
        inventory: {
            items: [
                "consumable.healing-potion.normal",
                "consumable.poison.small",
            ],
        },
        personality: {
            traits: ["cruel", "deceptive", "greedy", "patient", "vengeful"],
            background: ["witch"],
        },
        labels: ["bog-witch"],
    },
    {
        id: "item.swamp.swamp-herb",
        populatorType: "item",
        name: "Swamp Herb",
        tier: ["common", "rare"],
        type: "material",
        labels: ["herb", "swamp-herb"],
    },
    {
        id: "item.swamp.mud-boots",
        populatorType: "item",
        name: "Mud Boots",
        tier: "common",
        type: "boots",
        boots: { defense: { min: 5, max: 10 } },
        labels: ["mud-boots"],
    },
    {
        id: "weapon.animal.swamp-monster-claws",
        populatorType: "item",
        name: "Swamp Monster Claws",
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 20, max: 40 } },
        lootable: false,
    },
    {
        id: "armor.animal.swamp-monster-skin",
        populatorType: "item",
        name: "Swamp Monster Skin",
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 25, max: 50 } },
        lootable: false,
    },
    {
        id: "weapon.animal.alligator-teeth",
        populatorType: "item",
        name: "Alligator Teeth",
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 10, max: 20 } },
        lootable: false,
    },
    {
        id: "room.tavern.bedroom",
        populatorType: "children",
        name: "Tavern Bedroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "bedroom" },
    },
    {
        id: "room.tavern.kitchen",
        populatorType: "children",
        name: "Tavern Kitchen",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "kitchen" },
    },
    {
        id: "room.tavern.cellar",
        populatorType: "children",
        name: "Tavern Cellar",
        distance: 1,
        humidity: "humid",
        temperature: ["cool", "cold"],
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "npc.tavern.tavern-keeper",
        populatorType: "npc",
        name: "Tavern Keeper",
        health: { status: "healthy", points: 1000, max: 1000 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [100, 250, 400, 800],
            items: [
                "household.kitchen-item",
                "food.simple-food",
                "drink.simple-drink",
            ],
        },
        personality: {
            traits: [
                "brave",
                "cheerful",
                "adventurous",
                "compassionate",
                "disciplined",
                "honest",
                "humble",
            ],
            background: "innkeeper",
        },
        quests: [
            {
                type: "deliver",
                cargo: { oneOf: ["food.simple-food", "drink.simple-drink"] },
            },
        ],
    },
    {
        id: "building.tavern",
        populatorType: "children",
        name: "Tavern",
        distance: 5,
        humidity: ["normal", "humid"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "base" },
        labels: ["tavern"],
    },
    {
        id: "npc.town-hall.mayor",
        populatorType: "npc",
        name: "Mayor",
        health: { status: "healthy", points: 800, max: 800 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.elegant-clothing",
            boots: "boots.rare.elegant-boots",
            helmet: "helmet.rare.elegant-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [1000, 3000, 8000],
            items: [
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
            ],
        },
        personality: {
            traits: [
                "kind",
                "generous",
                "loyal",
                "curious",
                "empathetic",
                "cheerful",
                "compassionate",
            ],
            background: "diplomat",
        },
    },
    {
        id: "building.town-hall",
        populatorType: "children",
        name: "Town Hall",
        distance: 5,
        humidity: ["normal"],
        temperature: ["mild"],
        type: "building",
        building: { buildingType: "town-hall" },
        labels: ["town-hall"],
    },
    {
        id: "settlement.village",
        populatorType: "children",
        name: "Village",
        distance: 10,
        humidity: ["dry", "normal", "humid", "wet"],
        temperature: ["cool", "cold", "mild", "warm"],
        type: "settlement",
        settlement: { settlementType: "village" },
    },
    {
        id: "street.village-street",
        populatorType: "children",
        name: "Village Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-main-street",
        populatorType: "children",
        name: "Main Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["main-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-church-street",
        populatorType: "children",
        name: "Church Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["church-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-farm-street",
        populatorType: "children",
        name: "Farm Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["farm-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "npc.village.peasant",
        populatorType: "npc",
        name: "Peasant",
        health: { status: "healthy", points: [150, 200], max: 200 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
        },
        inventory: { gold: [10, 20, 50] },
        personality: {
            traits: [
                "apathetic",
                "arrogant",
                "cowardly",
                "indifferent",
                "pessimistic",
                "selfish",
            ],
            background: "peasant",
        },
    },
    {
        id: "npc.village.guard",
        populatorType: "npc",
        name: "Peasant",
        health: { status: "healthy", points: [150, 200], max: 200 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            boots: "boots.rare.nice-boots",
            helmet: "helmet.rare.nice-helmet",
            weapon: {
                oneOf: [
                    "weapon.rare.nice-sword",
                    "weapon.rare.nice-axe",
                    "weapon.rare.nice-bow",
                    "weapon.rare.nice-crossbow",
                ],
            },
        },
        inventory: {
            gold: [100, 200, 300],
            items: [
                "food.simple-food",
                "food.simple-food",
                "drink.simple-drink",
                "drink.simple-drink",
            ],
        },
        personality: {
            traits: [
                "brave",
                "cheerful",
                "adventurous",
                "compassionate",
                "disciplined",
                "honest",
                "humble",
            ],
            background: "peasant",
        },
    },
    {
        id: "weapon.common.simple-sword",
        populatorType: "item",
        name: ["Sword", "Simple Sword", "Rusty Sword"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 10, max: 20 } },
    },
    {
        id: "weapon.rare.nice-sword",
        populatorType: "item",
        name: ["Nice Steel Sword", "Nice Iron Sword"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 50, max: 80 } },
    },
    {
        id: "weapon.common.simple-axe",
        populatorType: "item",
        name: ["Axe", "Simple Axe", "Rusty Axe"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 10, max: 30 } },
    },
    {
        id: "weapon.rare.nice-axe",
        populatorType: "item",
        name: ["Nice Steel Axe", "Nice Iron Axe"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 60, max: 100 } },
    },
    {
        id: "weapon.common.simple-knife",
        populatorType: "item",
        name: ["Knife", "Simple Knife", "Rusty Knife"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 5, max: 15 } },
    },
    {
        id: "weapon.common.simple-dagger",
        populatorType: "item",
        name: ["Dagger", "Simple Dagger", "Rusty Dagger"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "dagger", damage: { min: 5, max: 20 } },
    },
    {
        id: "weapon.common.simple-bow",
        populatorType: "item",
        name: ["Bow", "Simple Bow", "Lame Bow"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 5, max: 20 } },
    },
    {
        id: "weapon.rare.nice-bow",
        populatorType: "item",
        name: ["Nice Bow", "Nice Longbow"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 20, max: 50 } },
    },
    {
        id: "weapon.common.simple-crossbow",
        populatorType: "item",
        name: ["Crossbow", "Simple Crossbow", "Lame Crossbow"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "crossbow", damage: { min: 5, max: 30 } },
    },
    {
        id: "weapon.rare.nice-crossbow",
        populatorType: "item",
        name: ["Nice Crossbow", "Nice Heavy Crossbow"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "crossbow", damage: { min: 30, max: 70 } },
    },
    {
        id: "weapon.common.simple-staff",
        populatorType: "item",
        name: ["Staff", "Simple Staff", "Lame Staff"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 5, max: 30 } },
    },
    {
        id: "weapon.rare.nice-staff",
        populatorType: "item",
        name: ["Nice Staff", "Nice Heavy Staff"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "staff", damage: { min: 30, max: 70 } },
    },
    {
        id: "weapon.animal.wolf-paws",
        populatorType: "item",
        name: "Wolf Paws",
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 10, max: 15 } },
        lootable: false,
    },
    {
        id: "weapon.epic.amazing-staff",
        populatorType: "item",
        name: ["Powerful Steel Staff", "Blessed Iron Staff"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "staff",
            damage: { min: 100, max: 150 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [90, 500, 1000],
                    probability: 1,
                },
                {
                    name: "Superpower2",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [90, 500, 1000],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-sword",
        populatorType: "item",
        name: ["Powerful Steel Sword", "Blessed Iron Sword"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "sword",
            damage: { min: 100, max: 150 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-axe",
        populatorType: "item",
        name: ["Mighty Steel Axe", "Blessed Iron Axe"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "axe",
            damage: { min: 120, max: 180 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-knife",
        populatorType: "item",
        name: ["Sharp Steel Knife", "Blessed Iron Knife"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "knife",
            damage: { min: 60, max: 90 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-dagger",
        populatorType: "item",
        name: ["Poisonous Steel Dagger", "Blessed Iron Dagger"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "dagger",
            damage: { min: 70, max: 100 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-bow",
        populatorType: "item",
        name: ["Powerful Steel Bow", "Blessed Iron Bow"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "bow",
            damage: { min: 80, max: 120 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.epic.amazing-crossbow",
        populatorType: "item",
        name: ["Powerful Steel Crossbow", "Blessed Iron Crossbow"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "crossbow",
            damage: { min: 90, max: 130 },
            effects: [
                {
                    name: "Smite",
                    activation: ["when-attacking"],
                    type: ["damage"],
                    value: [10, 12, 15, 18, 20],
                    probability: 1,
                },
                {
                    name: "Smite",
                    activation: ["when-attacking", "when-defending"],
                    type: ["damage", "heal"],
                    value: [10, 12, 15, 18, 20],
                    probability: 0.2,
                },
            ],
        },
    },
    {
        id: "weapon.animal.scorpion-venom-claws",
        populatorType: "item",
        name: "Scorpion Venom Claws",
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 75, max: 100 } },
        noAi: true,
        lootable: false,
    },
    {
        id: "weapon.animal.spider-fangs",
        populatorType: "item",
        name: "Spider Fangs",
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 15, max: 25 } },
        lootable: false,
    },
    {
        id: "building.wizards-tower",
        populatorType: "children",
        name: "Wizard's Tower",
        distance: 5,
        humidity: ["normal", "dry"],
        temperature: ["mild", "cool"],
        type: "building",
        building: { buildingType: "house" },
        labels: ["wizards-tower"],
    },
    {
        id: "material.magical-material",
        populatorType: "item",
        name: "Magical Material",
        tier: "rare",
        type: "material",
        labels: ["magical"],
    },
    {
        id: "material.magical-dust",
        populatorType: "item",
        name: "Magical Dust",
        tier: "common",
        type: "material",
        labels: ["magical"],
    },
    {
        id: "npc.wizards-tower.wizard",
        populatorType: "npc",
        name: "Wizard",
        race: "human",
        stance: "friendly",
        health: { status: "healthy", points: 1000, max: 1000 },
        gear: {
            armor: "armor.rare.nice-armor",
            boots: "boots.rare.nice-boots",
            helmet: "helmet.rare.nice-helmet",
            weapon: "weapon.rare.nice-staff",
        },
        inventory: {
            gold: [1000, 2000, 3000],
            items: [
                "material.magical-material",
                "material.magical-material",
                "weapon.rare.nice-staff",
                "weapon.rare.nice-staff",
                "material.magical-dust",
                "material.magical-dust",
                "material.magical-dust",
            ],
        },
        personality: {
            traits: ["curious", "diligent", "patient", "optimistic", "humble"],
            background: "scholar",
        },
        labels: ["wizard"],
    },
    {
        id: "wizards-tower.scrolls",
        populatorType: "item",
        name: ["Scroll", "Magical Scroll"],
        tier: ["rare", "epic"],
        type: "consumable",
        oneOf: ["consumable.scroll.fireball", "consumable.scroll.lightning"],
        probability: 0.5,
    },
] as Array<INodePopulator>;
