import { INodePopulatorRule } from "./WorldGenerator2";

export const BuiltinRules: Array<INodePopulatorRule> = [
    {
        id: "alchemists-guild-alchemist",
        apply: "npc.alchemists-guild.alchemist",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "alchemists-guild",
    },
    {
        id: "alchemists-guild-materials",
        apply: "material.potion-ingredient",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "alchemists-guild",
    },
    {
        id: "alchemists-guild-herbs",
        apply: "material.herb",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "alchemists-guild",
    },
    {
        id: "alchemists-guild-equipment",
        apply: "household.potion-brewing-equipment",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "alchemists-guild",
    },
    {
        id: "bedroom-household-items",
        apply: "household.common-item",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
    },
    {
        id: "bedroom-chest",
        apply: "furniture.chest",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
        probability: 0.1,
    },
    {
        id: "bedroom-bed",
        apply: "furniture.bed",
        count: { min: 1, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
    },
    {
        id: "blacksmith-smith-npc",
        apply: "npc.blacksmith.smith",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "blacksmith",
    },
    {
        id: "blacksmith-raw-materials-iron",
        apply: "material.iron",
        count: { min: 3, max: 10 },
        hasType: "building",
        hasLabel: "blacksmith",
    },
    {
        id: "blacksmith-raw-materials-wood",
        apply: "material.wood",
        count: { min: 1, max: 3 },
        hasType: "building",
        hasLabel: "blacksmith",
    },
    {
        id: "blacksmith-raw-materials-copper",
        apply: "material.copper",
        count: { min: 0, max: 3 },
        hasType: "building",
        hasLabel: "blacksmith",
    },
    {
        id: "blacksmith-raw-materials-steel",
        apply: "material.steel",
        count: { min: 0, max: 3 },
        hasType: "building",
        hasLabel: "blacksmith",
    },
    {
        id: "cave-stones",
        apply: "material.cave.stone",
        count: { min: 2, max: 10 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "cave" },
        probability: 0.9,
    },
    {
        id: "cave-ores",
        apply: "material.cave.ore",
        count: { min: 1, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "cave" },
        probability: 0.5,
    },
    {
        id: "cave-spiders",
        apply: "npc.cave.giant-spider",
        count: { min: 1, max: 3 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "cave" },
        probability: 0.5,
    },
    {
        id: "cave-cave-paths",
        apply: "wilderness.cave",
        count: { min: 1, max: 2 },
        depth: { min: 0, max: 5 },
        probability: 0.5,
        hasType: "wilderness",
        wilderness: { hasWildernessType: "cave" },
    },
    {
        id: "church-artifacts-icons",
        apply: "artifact.religious-icon",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "church-artifacts-books",
        apply: "artifact.religious-book",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "church-npc-priest",
        apply: "npc.church.priest",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "desert-scorpions",
        apply: "npc.desert.scorpion",
        count: { min: 1, max: 3 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "desert" },
        probability: 0.7,
    },
    {
        id: "forest-dungeon",
        apply: "building.dungeon",
        count: { min: 1, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
        probability: 0.2,
    },
    {
        id: "forest-dungeon-undead",
        apply: "npc.dungeon.undead",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "dungeon" },
        hasLabel: "dungeon",
    },
    {
        id: "dungeon-loot-epic",
        apply: "item.dungeon.epic.loot",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "dungeon" },
        hasLabel: "dungeon",
        probability: 0.7,
    },
    {
        id: "dungeon-loot-rare",
        apply: "item.dungeon.rare.loot",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "dungeon" },
        hasLabel: "dungeon",
        probability: 0.9,
    },
    {
        id: "engineers-guild-engineer",
        apply: "npc.engineers-guild.engineer",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "engineers-guild",
    },
    {
        id: "engineers-guild-materials",
        apply: "material.common",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "engineers-guild",
    },
    {
        id: "engineers-guild-iron",
        apply: "material.iron",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "engineers-guild",
    },
    {
        id: "engineers-guild-steel",
        apply: "material.steel",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "engineers-guild",
    },
    {
        id: "engineers-guild-wood",
        apply: "material.wood",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "engineers-guild",
    },
    {
        id: "forest-forest-paths",
        apply: "wilderness.forest",
        count: { min: 1, max: 3 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-village-paths",
        apply: "settlement.village",
        count: { min: 0, max: 2 },
        depth: { min: 2, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-wolves",
        apply: "npc.forest.wolf",
        count: { min: 0, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-swamp-paths",
        apply: "wilderness.swamp",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-desert-paths",
        apply: "wilderness.desert",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "desert-forest-paths",
        apply: "wilderness.forest",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "desert" },
    },
    {
        id: "forest-herbs",
        apply: "item.swamp.swamp-herb",
        count: { min: 1, max: 2 },
        probability: 0.25,
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-wood",
        apply: "material.wood",
        count: { min: 1, max: 2 },
        probability: 0.5,
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "kitchen-items",
        apply: "household.kitchen-item",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "kitchen-food-ingredients",
        apply: "material.food-ingredient",
        count: { min: 1, max: 2 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "kitchen-drink-ingredients",
        apply: "material.drink-ingredient",
        count: { min: 1, max: 2 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "house-bedrooms",
        apply: "room.house.bedroom",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-kitchens",
        apply: "room.house.kitchen",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-storerooms",
        apply: "room.house.storage",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "mine-miners",
        apply: "npc.mine.miner",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "base" },
        hasLabel: "mine",
    },
    {
        id: "mine-mining-equipment",
        apply: "household.mining-equipment",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "base" },
        hasLabel: "mine",
    },
    {
        id: "mine-ores",
        apply: "material.ore",
        count: { min: 5, max: 10 },
        hasType: "building",
        building: { hasBuildingType: "base" },
        hasLabel: "mine",
    },
    {
        id: "mine-crude-rocks",
        apply: "material.crude-rock",
        count: { min: 5, max: 10 },
        hasType: "building",
        building: { hasBuildingType: "base" },
        hasLabel: "mine",
    },
    {
        id: "pharmacy-npc-pharmacist",
        apply: "npc.pharmacy.pharmacist",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-materials-herbs",
        apply: "material.herb",
        count: { min: 0, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-materials-potion-ingredients",
        apply: "material.potion-ingredient",
        count: { min: 0, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-household-potion-brewing-equipment",
        apply: "household.potion-brewing-equipment",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "mountain-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 1, max: 3 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "mountain-forest-paths",
        apply: "wilderness.forest",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "mountain-wolves",
        apply: "npc.mountain.wolf",
        count: { min: 0, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "mountain-mine",
        apply: "building.mine",
        count: { min: 1, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
        probability: 0.25,
    },
    {
        id: "mountain-cave-paths",
        apply: "wilderness.cave",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "cave-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "cave" },
    },
    {
        id: "mountain-crude-rocks",
        apply: "material.crude-rock",
        count: { min: 1, max: 3 },
        probability: 0.5,
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "river-fish",
        apply: "npc.river.fish",
        count: { min: 2, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "river" },
        probability: 0.8,
    },
    {
        id: "river-forest-paths",
        apply: "wilderness.forest",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "river" },
    },
    {
        id: "forest-river-paths",
        apply: "wilderness.river",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "river-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "river" },
    },
    {
        id: "mountain-river-paths",
        apply: "wilderness.river",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "cellar-food",
        apply: "food.simple-food",
        count: { min: 1, max: 5 },
        hasType: "room",
        room: { hasRoomType: "storage" },
    },
    {
        id: "cellar-drinks",
        apply: "drink.simple-drink",
        count: { min: 1, max: 5 },
        hasType: "room",
        room: { hasRoomType: "storage" },
    },
    {
        id: "root-forests",
        apply: "wilderness.forest",
        count: { min: 1, max: 5 },
        hasType: "root",
    },
    {
        id: "root-mountains",
        apply: "wilderness.mountain",
        count: { min: 1, max: 5 },
        hasType: "root",
    },
    {
        id: "swamp-swamp-monsters",
        apply: "npc.swamp.swamp-monster",
        count: { min: 1, max: 2 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
        probability: 0.5,
    },
    {
        id: "swamp-alligators",
        apply: "npc.swamp.alligator",
        count: { min: 1, max: 2 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
        probability: 0.25,
    },
    {
        id: "swamp-bog-witch",
        apply: "npc.swamp.bog-witch",
        count: { min: 1, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
        probability: 0.1,
    },
    {
        id: "swamp-swamp-herbs",
        apply: "item.swamp.swamp-herb",
        count: { min: 2, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
        probability: 0.9,
    },
    {
        id: "swamp-mud-boots",
        apply: "item.swamp.mud-boots",
        count: { min: 0, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
        probability: 0.6,
    },
    {
        id: "swamp-forest-paths",
        apply: "wilderness.forest",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "swamp" },
    },
    {
        id: "forest-swamp-paths",
        apply: "wilderness.swamp",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "tavern-bedrooms",
        apply: "room.tavern.bedroom",
        count: { min: 1, max: 2 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-kitchens",
        apply: "room.tavern.kitchen",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-cellars",
        apply: "room.tavern.cellar",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-food",
        apply: "food.simple-food",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-drinks",
        apply: "drink.simple-drink",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-kitchen-items",
        apply: "household.kitchen-item",
        count: { min: 0, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-tavern-keeper",
        apply: "npc.tavern.tavern-keeper",
        count: { min: 1, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "tavern-merchant",
        apply: "npc.merchant",
        count: { min: 0, max: 1 },
        hasType: "building",
        hasLabel: "tavern",
    },
    {
        id: "village-street-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 2 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-merchant",
        apply: "npc.merchant",
        count: { min: 0, max: 2 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-wizards-tower",
        apply: "building.wizards-tower",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-pharmacy",
        apply: "building.pharmacy",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-alchemists-guild",
        apply: "building.alchemists-guild",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-engineers-guild",
        apply: "building.engineers-guild",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "town-hall-mayor",
        apply: "npc.town-hall.mayor",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-scuplture",
        apply: "artifact.sculpture",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-painting",
        apply: "artifact.painting",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-book",
        apply: "artifact.book",
        count: { min: 0, max: 4 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "village-streets",
        apply: "street.village-street",
        count: { min: 1, max: 2 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-main-street",
        apply: "street.village-main-street",
        count: { min: 1, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-church-street",
        apply: "street.village-church-street",
        count: { min: 0, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-farm-street",
        apply: "street.village-farm-street",
        count: { min: 0, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-street-houses",
        apply: "building.house",
        count: { min: 2, max: 4 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-taverns",
        apply: "building.tavern",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-blacksmithes",
        apply: "building.blacksmith",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-main-street-town-hall",
        apply: "building.town-hall",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-main-street-pharmacy",
        apply: "building.pharmacy",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-church-street-church",
        apply: "building.church",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "church-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-farm-street-farms",
        apply: "building.farm",
        count: { min: 1, max: 4 },
        hasType: "street",
        hasLabel: "farm-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-settlement-guards",
        apply: "npc.village.guard",
        count: { min: 2, max: 3 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-main-street-engineers-guild",
        apply: "building.engineers-guild",
        count: { min: 0, max: 2 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-main-street-wizards-tower",
        apply: "building.wizards-tower",
        count: { min: 0, max: 1 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "wizards-tower-wizard",
        apply: "npc.wizards-tower.wizard",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
        hasLabel: "wizards-tower",
    },
    {
        id: "wizards-tower-magical-materials",
        apply: "material.magical-material",
        count: { min: 2, max: 5 },
        hasType: "building",
        building: { hasBuildingType: "house" },
        hasLabel: "wizards-tower",
    },
    {
        id: "wizards-tower-magical-dust",
        apply: "material.magical-dust",
        count: { min: 5, max: 10 },
        hasType: "building",
        building: { hasBuildingType: "house" },
        hasLabel: "wizards-tower",
    },
    {
        id: "wizards-tower-scrolls",
        apply: "wizards-tower.scrolls",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "house" },
        hasLabel: "wizards-tower",
    },
] as Array<INodePopulatorRule>;
