import { INodePopulatorRule } from "./WorldGenerator2";

export const BuiltinRules: Array<INodePopulatorRule> = [
    {
        id: "bedroom-household-items",
        apply: "household.common-item",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
    },
    {
        id: "bedroom-chest",
        apply: "furniture.chest",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
        probability: 0.1,
    },
    {
        id: "bedroom-bed",
        apply: "furniture.bed",
        count: { min: 1, max: 1 },
        hasType: "room",
        room: { hasRoomType: "bedroom" },
    },
    {
        id: "blacksmith-smith-npc",
        apply: "npc.blacksmith.smith",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "blacksmith" },
    },
    {
        id: "blacksmith-raw-materials-iron",
        apply: "material.iron",
        count: { min: 3, max: 10 },
        hasType: "building",
        building: { hasBuildingType: "blacksmith" },
    },
    {
        id: "blacksmith-raw-materials-wood",
        apply: "material.wood",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "blacksmith" },
    },
    {
        id: "blacksmith-raw-materials-copper",
        apply: "material.copper",
        count: { min: 0, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "blacksmith" },
    },
    {
        id: "blacksmith-raw-materials-steel",
        apply: "material.steel",
        count: { min: 0, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "blacksmith" },
    },
    {
        id: "church-artifacts-icons",
        apply: "artifact.religious-icon",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "church-artifacts-books",
        apply: "artifact.religious-book",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "church-npc-priest",
        apply: "npc.church.priest",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "church" },
    },
    {
        id: "forest-forest-paths",
        apply: "wilderness.forest",
        count: { min: 1, max: 3 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-village-paths",
        apply: "settlement.village",
        count: { min: 0, max: 2 },
        depth: { min: 2, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "forest-wolves",
        apply: "npc.forest.wolf",
        count: { min: 0, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "forest" },
    },
    {
        id: "house-bedrooms",
        apply: "room.house.bedroom",
        count: { min: 1, max: 3 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-kitchens",
        apply: "room.house.kitchen",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-storerooms",
        apply: "room.house.storage",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "house-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "house" },
    },
    {
        id: "kitchen-items",
        apply: "household.kitchen-item",
        count: { min: 0, max: 1 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "kitchen-food-ingredients",
        apply: "material.food-ingredient",
        count: { min: 1, max: 2 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "kitchen-drink-ingredients",
        apply: "material.drink-ingredient",
        count: { min: 1, max: 2 },
        hasType: "room",
        room: { hasRoomType: "kitchen" },
    },
    {
        id: "mountain-mountain-paths",
        apply: "wilderness.mountain",
        count: { min: 1, max: 3 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "mountain-forest-paths",
        apply: "wilderness.forest",
        count: { min: 0, max: 1 },
        depth: { min: 0, max: 5 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "mountain-wolves",
        apply: "npc.mountain.wolf",
        count: { min: 0, max: 1 },
        hasType: "wilderness",
        wilderness: { hasWildernessType: "mountain" },
    },
    {
        id: "pharmacy-npc-pharmacist",
        apply: "npc.pharmacy.pharmacist",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-materials-herbs",
        apply: "material.herb",
        count: { min: 0, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-materials-potion-ingredients",
        apply: "material.potion-ingredient",
        count: { min: 0, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "pharmacy-household-potion-brewing-equipment",
        apply: "household.potion-brewing-equipment",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "store" },
        hasLabel: "pharmacy",
    },
    {
        id: "cellar-food",
        apply: "food.simple-food",
        count: { min: 1, max: 5 },
        hasType: "room",
        room: { hasRoomType: "storage" },
    },
    {
        id: "cellar-drinks",
        apply: "drink.simple-drink",
        count: { min: 1, max: 5 },
        hasType: "room",
        room: { hasRoomType: "storage" },
    },
    {
        id: "root-forests",
        apply: "wilderness.forest",
        count: { min: 1, max: 5 },
        hasType: "root",
    },
    {
        id: "root-mountains",
        apply: "wilderness.mountain",
        count: { min: 1, max: 5 },
        hasType: "root",
    },
    {
        id: "tavern-bedrooms",
        apply: "room.tavern.bedroom",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-kitchens",
        apply: "room.tavern.kitchen",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-cellars",
        apply: "room.tavern.cellar",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-food",
        apply: "food.simple-food",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-drinks",
        apply: "drink.simple-drink",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-kitchen-items",
        apply: "household.kitchen-item",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-tavern-keeper",
        apply: "npc.tavern.tavern-keeper",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "tavern-merchant",
        apply: "npc.merchant",
        count: { min: 0, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "tavern" },
    },
    {
        id: "town-hall-mayor",
        apply: "npc.town-hall.mayor",
        count: { min: 1, max: 1 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-scuplture",
        apply: "artifact.sculpture",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-painting",
        apply: "artifact.painting",
        count: { min: 1, max: 2 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "town-hall-artifacts-book",
        apply: "artifact.book",
        count: { min: 0, max: 4 },
        hasType: "building",
        building: { hasBuildingType: "town-hall" },
    },
    {
        id: "village-street-peasant",
        apply: "npc.village.peasant",
        count: { min: 0, max: 2 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-merchant",
        apply: "npc.merchant",
        count: { min: 0, max: 2 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-streets",
        apply: "street.village-street",
        count: { min: 1, max: 2 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-main-street",
        apply: "street.village-main-street",
        count: { min: 1, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-church-street",
        apply: "street.village-church-street",
        count: { min: 0, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-farm-street",
        apply: "street.village-farm-street",
        count: { min: 0, max: 1 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
    {
        id: "village-street-houses",
        apply: "building.house",
        count: { min: 2, max: 4 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-taverns",
        apply: "building.tavern",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-street-blacksmithes",
        apply: "building.blacksmith",
        count: { min: 0, max: 1 },
        hasType: "street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-main-street-town-hall",
        apply: "building.town-hall",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-main-street-pharmacy",
        apply: "building.pharmacy",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "main-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-church-street-church",
        apply: "building.church",
        count: { min: 1, max: 1 },
        hasType: "street",
        hasLabel: "church-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-farm-street-farms",
        apply: "building.farm",
        count: { min: 1, max: 4 },
        hasType: "street",
        hasLabel: "farm-street",
        street: { hasStreetType: "village-street" },
    },
    {
        id: "village-settlement-guards",
        apply: "npc.village.guard",
        count: { min: 2, max: 3 },
        hasType: "settlement",
        settlement: { hasSettlementType: "village" },
    },
] as Array<INodePopulatorRule>;
