import { INodePopulator } from "./WorldGenerator2";

export const BuiltinPopulators: Array<INodePopulator> = [
    {
        id: "populators.builtin.common-armor.simple-armor",
        populatorType: "item",
        name: ["Simple Chestplate", "Simple Armor", "Simple Leather Armor"],
        tier: "common",
        type: "armor",
        armor: { defense: { min: 2, max: 10 } },
    },
    {
        id: "armor.common.simple-clothing",
        populatorType: "item",
        name: ["Simple Clothing", "Simple Garment", "Simple Outfit"],
        tier: "common",
        type: "armor",
        armor: { defense: { min: 0, max: 3 } },
    },
    {
        id: "armor.rare.elegant-clothing",
        populatorType: "item",
        name: ["Elegant Clothing", "Noble Elegant Garment", "Elegant Outfit"],
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 25, max: 50 } },
    },
    {
        id: "armor.rare.nice-armor",
        populatorType: "item",
        name: ["Nice Steel Armor", "Nice Iron Armor"],
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 30, max: 150 } },
    },
    {
        id: "armor.rare.priest-robe",
        populatorType: "item",
        name: "Black Robe of Priest",
        tier: "rare",
        type: "armor",
        armor: { defense: { min: 1, max: 5 } },
    },
    {
        id: "armor.animal.wolf-fur",
        populatorType: "item",
        name: "Wolf Fur",
        tier: "common",
        type: "armor",
        armor: { defense: { min: 10, max: 13 } },
        lootable: false,
    },
    {
        id: "building.blacksmith",
        populatorType: "children",
        name: "Blacksmith Workshop",
        distance: 5,
        humidity: "dry",
        temperature: ["warm", "hot"],
        type: "building",
        building: { buildingType: "blacksmith" },
    },
    {
        id: "npc.blacksmith.smith",
        populatorType: "npc",
        name: "Smith",
        health: { status: "healthy", points: 2000, max: 2000 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.rare.elegant-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: ["weapon.rare.nice-sword", "weapon.rare.nice-axe"],
            },
        },
        inventory: {
            gold: [4000, 10000],
            items: [
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
                {
                    oneOf: [
                        "weapon.rare.nice-sword",
                        "weapon.rare.nice-axe",
                        "armor.rare.nice-armor",
                    ],
                },
            ],
        },
        personality: {
            traits: [
                "cautious",
                "indifferent",
                "disciplined",
                "apatethic",
                "patient",
                "honest",
            ],
            background: "blacksmith",
        },
    },
    {
        id: "artifact.sculpture",
        populatorType: "item",
        name: [
            "Beautiful Stone Sculpture",
            "Exquisite Marvel Sculpture",
            "Nice Bronze Sculpture",
        ],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.map",
        populatorType: "item",
        name: ["Map of Land", "Map of the World"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.letter",
        populatorType: "item",
        name: "Handwritten Letter",
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.book",
        populatorType: "item",
        name: ["Book on History", "Book on Magic", "Book on Science"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.painting",
        populatorType: "item",
        name: ["Beautiful Painting", "Exquisite Painting", "Nice Painting"],
        tier: ["rare"],
        type: "artifact",
    },
    {
        id: "artifact.religious-icon",
        populatorType: "item",
        name: ["Religious Icon", "Holy Icon", "Sacred Icon"],
        tier: ["common"],
        type: "artifact",
    },
    {
        id: "artifact.religious-book",
        populatorType: "item",
        name: ["Religious Book", "Religious Singing Book", "Sacred Book"],
        tier: ["common"],
        type: "artifact",
    },
    {
        id: "boots.common.simple-boots",
        populatorType: "item",
        name: ["Simple Boots", "Simple Footwear", "Simple Shoes"],
        tier: "common",
        type: "boots",
        boots: { defense: { min: 0, max: 3 } },
    },
    {
        id: "boots.rare.elegant-boots",
        populatorType: "item",
        name: ["Elegant Boots", "Noble Elegant Footwear", "Elegant Shoes"],
        tier: "rare",
        type: "boots",
        boots: { defense: { min: 20, max: 50 } },
    },
    {
        id: "boots.rare.nice-boots",
        populatorType: "item",
        name: ["Nice Steel Boots", "Polished Iron Boots", "Nice Boots"],
        tier: "rare",
        type: "boots",
        boots: { defense: { min: 30, max: 60 } },
    },
    {
        id: "building.church",
        populatorType: "children",
        name: "Church",
        distance: 5,
        humidity: ["dry", "normal"],
        temperature: ["mild", "cool", "cold"],
        type: "building",
        building: { buildingType: "church" },
    },
    {
        id: "npc.church.priest",
        populatorType: "npc",
        name: "Priest",
        health: { status: "healthy", points: 100, max: 100 },
        race: "human",
        stance: "friendly",
        gear: { armor: "armor.rare.priest-robe" },
        personality: {
            traits: ["kind", "patient", "loyal", "forgiving", "compassionate"],
            background: "priest",
        },
        inventory: {
            gold: [0, 10, 25, 50, 100],
            items: [{ oneOf: ["artifact.religious-book"] }],
        },
    },
    {
        id: "consumable.healing-potion.small",
        populatorType: "item",
        name: ["Small Healing Potion", "Tiny Potion of Healing"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [10, 25] }],
        },
    },
    {
        id: "consumable.healing-potion.normal",
        populatorType: "item",
        name: ["Healing Potion", "Potion of Healing"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [100, 150] }],
        },
    },
    {
        id: "consumable.healing-potion.large",
        populatorType: "item",
        name: ["Large Healing Potion", "Big Potion of Healing"],
        tier: "epic",
        type: "consumable",
        consumable: {
            effects: [{ name: "Heal", type: "heal", value: [500, 750] }],
        },
    },
    {
        id: "consumable.poison.small",
        populatorType: "item",
        name: ["Small Vile of Poison", "Poison Vile"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Poison Yourself",
                    type: "damage-self",
                    value: [10, 25],
                },
            ],
        },
    },
    {
        id: "consumable.poison.normal",
        populatorType: "item",
        name: ["Vile of Poison", "Glass of Poison"],
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Poison Yourself",
                    type: "damage-self",
                    value: [100, 150],
                },
            ],
        },
    },
    {
        id: "consumable.dynamite",
        populatorType: "item",
        name: "Dynamite Stick",
        tier: "rare",
        type: "consumable",
        consumable: {
            effects: [
                {
                    name: "Explode Enemy",
                    type: "damage-enemy",
                    value: [100, 150],
                },
            ],
        },
    },
    {
        id: "drink.simple-drink",
        populatorType: "item",
        name: [
            "Drinkable Liquid",
            "Cup of Refresher",
            "Tasty Beverage",
            "Simple Drink",
        ],
        tier: "common",
        type: "drink",
    },
    {
        id: "building.farm",
        populatorType: "children",
        name: "Farm",
        distance: 5,
        humidity: ["normal", "humid"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "farm" },
    },
    {
        id: "room.farm.granary",
        populatorType: "children",
        name: "Granary",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "food.simple-food",
        populatorType: "item",
        name: ["Edible Food", "Tasty Snack", "Healthy Food", "Simple Meal"],
        tier: "common",
        type: "food",
    },
    {
        id: "wilderness.forest",
        populatorType: "children",
        name: "Forest",
        distance: 20,
        humidity: ["normal", "humid", "wet"],
        temperature: ["mild", "cool", "cold"],
        type: "wilderness",
        wilderness: { wildernessType: "forest" },
    },
    {
        id: "npc.forest.wolf",
        populatorType: "npc",
        name: ["Wolf", "Common Wolf", "Forest Wolf"],
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 250, max: 250 },
        gear: {
            weapon: "weapon.animal.wolf-paws",
            armor: "armor.animal.wolf-fur",
        },
    },
    {
        id: "helmet.common.simple-helmet",
        populatorType: "item",
        name: ["Simple Helmet", "Simple Headgear", "Simple Hat"],
        tier: "common",
        type: "helmet",
        helmet: { defense: { min: 0, max: 3 } },
    },
    {
        id: "helmet.rare.elegant-helmet",
        populatorType: "item",
        name: ["Elegant Headwear", "Noble Elegant Hat"],
        tier: "rare",
        type: "helmet",
        helmet: { defense: { min: 10, max: 20 } },
    },
    {
        id: "helmet.rare.nice-helmet",
        populatorType: "item",
        name: ["Nice Steel Helmet", "Polished Iron Helmet"],
        tier: "rare",
        type: "helmet",
        helmet: { defense: { min: 20, max: 30 } },
    },
    {
        id: "building.house",
        populatorType: "children",
        name: "House",
        distance: 5,
        humidity: ["dry", "normal", "humid"],
        temperature: ["cool", "mild", "warm", "hot"],
        type: "building",
        building: { buildingType: "house" },
    },
    {
        id: "room.house.bedroom",
        populatorType: "children",
        name: "Bedroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "bedroom" },
    },
    {
        id: "room.house.kitchen",
        populatorType: "children",
        name: "Kitchen",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "kitchen" },
    },
    {
        id: "room.house.storage",
        populatorType: "children",
        name: "Storeroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "household.common-item",
        populatorType: "item",
        name: ["Household Item", "Household Tool"],
        tier: "common",
        type: "household",
    },
    {
        id: "household.kitchen-item",
        populatorType: "item",
        name: [
            "Kitchen Tool",
            "Kitchen Container",
            "Kitchen Equipment",
            "Kitchen Utensil",
        ],
        tier: "common",
        type: "household",
    },
    {
        id: "furniture.bed",
        populatorType: "item",
        name: "Bed",
        tier: "common",
        type: "household",
        static: true,
    },
    {
        id: "furniture.chest",
        populatorType: "item",
        name: ["Chest", "Locker", "Box"],
        tier: "common",
        type: "household",
        static: true,
        contains: [
            {
                probability: 0.8,
                name: "Common Household Tool",
                tier: "common",
                type: "household",
            },
            {
                probability: 0.25,
                name: "Rare Household Tool",
                tier: "rare",
                type: "household",
            },
        ],
    },
    {
        id: "household.religious-item",
        populatorType: "item",
        name: ["Religious Item", "Faith Item", "Sacred Item"],
        tier: ["common", "rare"],
        type: "household",
    },
    {
        id: "household.potion-brewing-equipment",
        populatorType: "item",
        name: [
            "Potion Brewing Equipment",
            "Alchemy Set",
            "Brewing Apparatus",
            "Cauldron",
            "Distillation Kit",
        ],
        tier: ["common", "rare"],
        type: "household",
    },
    {
        id: "material.wood",
        populatorType: "item",
        name: [
            "Wood",
            "Lumber",
            "Timber",
            "Wooden Material",
            "Small Wooden Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.stone",
        populatorType: "item",
        name: ["Stone", "Rock", "Pebble", "Small Stone", "Small Rock"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.iron",
        populatorType: "item",
        name: ["Iron", "Iron Ingot", "Iron Material", "Small Iron Material"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.copper",
        populatorType: "item",
        name: [
            "Copper",
            "Copper Ingot",
            "Copper Material",
            "Small Copper Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.steel",
        populatorType: "item",
        name: [
            "Steel",
            "Steel Ingot",
            "Steel Material",
            "Small Steel Material",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.common",
        populatorType: "item",
        name: [
            "Common Material",
            "Common Resource",
            "Some Material",
            "Some Resource",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.food-ingredient",
        populatorType: "item",
        name: [
            "Spice",
            "Raw Meat",
            "Raw Vegetable",
            "Raw Fruit",
            "Raw Grain",
            "Mushroom",
            "Fish",
            "Food Ingredient",
        ],
        tier: "common",
        type: "material",
    },
    {
        id: "material.drink-ingredient",
        populatorType: "item",
        name: ["Water", "Milk", "Juice", "Drink Ingredient"],
        tier: "common",
        type: "material",
    },
    {
        id: "material.trade-commodity",
        populatorType: "item",
        name: [
            "Trade Commodity",
            "Trade Good",
            "Trade Material",
            "Trade Resource",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "material.herb",
        populatorType: "item",
        name: [
            "Herb",
            "Medicinal Herb",
            "Healing Herb",
            "Rare Herb",
            "Common Herb",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "material.potion-ingredient",
        populatorType: "item",
        name: [
            "Potion Ingredient",
            "Brewing Ingredient",
            "Alchemical Ingredient",
            "Magical Ingredient",
        ],
        tier: ["common", "rare"],
        type: "material",
    },
    {
        id: "npc.merchant",
        populatorType: "npc",
        name: "Merchant",
        health: { status: "healthy", points: [150, 200, 300], max: 300 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [500, 700, 1200],
            items: [
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
                "material.trade-commodity",
            ],
        },
        personality: {
            traits: [
                "adventurous",
                "brave",
                "diligent",
                "disciplined",
                "optimistic",
            ],
            background: "merchant",
        },
    },
    {
        id: "wilderness.mountain",
        populatorType: "children",
        name: "Mountain",
        distance: 50,
        humidity: ["normal", "dry"],
        temperature: ["cool", "cold", "freezing"],
        type: "wilderness",
        wilderness: { wildernessType: "mountain" },
    },
    {
        id: "npc.mountain.wolf",
        populatorType: "npc",
        name: ["Wolf", "Common Wolf", "Mountain Wolf"],
        race: "animal",
        stance: "hostile",
        health: { status: "healthy", points: 750, max: 750 },
        gear: {
            weapon: "weapon.animal.wolf-paws",
            armor: "armor.animal.wolf-fur",
        },
    },
    {
        id: "building.pharmacy",
        populatorType: "children",
        name: "Pharmacy",
        distance: 5,
        humidity: ["normal"],
        temperature: ["mild", "cool"],
        type: "building",
        building: { buildingType: "store" },
        labels: ["pharmacy"],
    },
    {
        id: "npc.pharmacy.pharmacist",
        populatorType: "npc",
        name: "Pharmacist",
        health: { status: "healthy", points: 100, max: 100 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            helmet: "helmet.rare.nice-helmet",
            boots: "boots.rare.nice-boots",
            weapon: "weapon.rare.nice-staff",
        },
        personality: {
            traits: [
                "kind",
                "honest",
                "generous",
                "patient",
                "humble",
                "empathetic",
            ],
            background: "healer",
        },
        inventory: {
            gold: [500, 1000, 1500, 2000, 3000],
            items: [
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                {
                    oneOf: [
                        "consumable.healing-potion.small",
                        "consumable.healing-potion.normal",
                        "consumable.poison.small",
                        "consumable.poison.normal",
                    ],
                },
                { oneOf: ["material.herb", "material.potion-ingredient"] },
                { oneOf: ["material.herb", "material.potion-ingredient"] },
            ],
        },
    },
    {
        id: "building.tavern",
        populatorType: "children",
        name: "Tavern",
        distance: 5,
        humidity: ["normal", "humid"],
        temperature: ["mild", "warm"],
        type: "building",
        building: { buildingType: "tavern" },
    },
    {
        id: "room.tavern.bedroom",
        populatorType: "children",
        name: "Tavern Bedroom",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "bedroom" },
    },
    {
        id: "room.tavern.kitchen",
        populatorType: "children",
        name: "Tavern Kitchen",
        distance: 1,
        humidity: "same",
        temperature: "same",
        type: "room",
        room: { roomType: "kitchen" },
    },
    {
        id: "room.tavern.cellar",
        populatorType: "children",
        name: "Tavern Cellar",
        distance: 1,
        humidity: "humid",
        temperature: ["cool", "cold"],
        type: "room",
        room: { roomType: "storage" },
    },
    {
        id: "npc.tavern.tavern-keeper",
        populatorType: "npc",
        name: "Tavern Keeper",
        health: { status: "healthy", points: 1000, max: 1000 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [100, 250, 400, 800],
            items: [
                "household.kitchen-item",
                "food.simple-food",
                "drink.simple-drink",
            ],
        },
        personality: {
            traits: [
                "brave",
                "cheerful",
                "adventurous",
                "compassionate",
                "disciplined",
                "honest",
                "humble",
            ],
            background: "innkeeper",
        },
        quests: [
            {
                type: "deliver",
                cargo: { oneOf: ["food.simple-food", "drink.simple-drink"] },
            },
        ],
    },
    {
        id: "building.town-hall",
        populatorType: "children",
        name: "Town Hall",
        distance: 5,
        humidity: ["normal"],
        temperature: ["mild"],
        type: "building",
        building: { buildingType: "town-hall" },
    },
    {
        id: "npc.town-hall.mayor",
        populatorType: "npc",
        name: "Mayor",
        health: { status: "healthy", points: 800, max: 800 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.elegant-clothing",
            boots: "boots.rare.elegant-boots",
            helmet: "helmet.rare.elegant-helmet",
            weapon: {
                oneOf: [
                    "weapon.common.simple-dagger",
                    "weapon.common.simple-sword",
                    "weapon.common.simple-axe",
                    "weapon.common.simple-bow",
                    "weapon.common.simple-crossbow",
                    "weapon.common.simple-staff",
                ],
            },
        },
        inventory: {
            gold: [1000, 3000, 8000],
            items: [
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
                {
                    oneOf: [
                        "artifact.sculpture",
                        "artifact.painting",
                        "artifact.book",
                        "artifact.letter",
                        "artifact.map",
                    ],
                },
            ],
        },
        personality: {
            traits: [
                "kind",
                "generous",
                "loyal",
                "curious",
                "empathetic",
                "cheerful",
                "compassionate",
            ],
            background: "diplomat",
        },
    },
    {
        id: "settlement.village",
        populatorType: "children",
        name: "Village",
        distance: 10,
        humidity: ["dry", "normal", "humid", "wet"],
        temperature: ["cool", "cold", "mild", "warm"],
        type: "settlement",
        settlement: { settlementType: "village" },
    },
    {
        id: "street.village-street",
        populatorType: "children",
        name: "Village Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-main-street",
        populatorType: "children",
        name: "Main Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["main-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-church-street",
        populatorType: "children",
        name: "Church Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["church-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "street.village-farm-street",
        populatorType: "children",
        name: "Farm Street",
        distance: 5,
        humidity: "same",
        temperature: "same",
        type: "street",
        labels: ["farm-street"],
        street: { streetType: "village-street" },
    },
    {
        id: "npc.village.peasant",
        populatorType: "npc",
        name: "Peasant",
        health: { status: "healthy", points: [150, 200], max: 200 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.common.simple-clothing",
            boots: "boots.common.simple-boots",
            helmet: "helmet.common.simple-helmet",
        },
        inventory: { gold: [10, 20, 50] },
        personality: {
            traits: [
                "apathetic",
                "arrogant",
                "cowardly",
                "indifferent",
                "pessimistic",
                "selfish",
            ],
            background: "peasant",
        },
    },
    {
        id: "npc.village.guard",
        populatorType: "npc",
        name: "Peasant",
        health: { status: "healthy", points: [150, 200], max: 200 },
        race: "human",
        stance: "friendly",
        gear: {
            armor: "armor.rare.nice-armor",
            boots: "boots.rare.nice-boots",
            helmet: "helmet.rare.nice-helmet",
            weapon: {
                oneOf: [
                    "weapon.rare.nice-sword",
                    "weapon.rare.nice-axe",
                    "weapon.rare.nice-bow",
                    "weapon.rare.nice-crossbow",
                ],
            },
        },
        inventory: {
            gold: [100, 200, 300],
            items: [
                "food.simple-food",
                "food.simple-food",
                "drink.simple-drink",
                "drink.simple-drink",
            ],
        },
        personality: {
            traits: [
                "brave",
                "cheerful",
                "adventurous",
                "compassionate",
                "disciplined",
                "honest",
                "humble",
            ],
            background: "peasant",
        },
    },
    {
        id: "weapon.common.simple-sword",
        populatorType: "item",
        name: ["Sword", "Simple Sword", "Rusty Sword"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 10, max: 20 } },
    },
    {
        id: "weapon.rare.nice-sword",
        populatorType: "item",
        name: ["Nice Steel Sword", "Nice Iron Sword"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 50, max: 80 } },
    },
    {
        id: "weapon.epic.amazing-sword",
        populatorType: "item",
        name: ["Powerful Steel Sword", "Blessed Iron Sword"],
        tier: "epic",
        type: "weapon",
        weapon: {
            weaponType: "sword",
            damage: { min: 100, max: 150 },
            effects: [
                {
                    name: "Superpower",
                    activation: ["when-attacking", "when-defending"],
                    type: ["heal", "damage"],
                    value: [100, 500, 1000],
                },
            ],
        },
    },
    {
        id: "weapon.common.simple-axe",
        populatorType: "item",
        name: ["Axe", "Simple Axe", "Rusty Axe"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 10, max: 30 } },
    },
    {
        id: "weapon.rare.nice-axe",
        populatorType: "item",
        name: ["Nice Steel Axe", "Nice Iron Axe"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "sword", damage: { min: 60, max: 100 } },
    },
    {
        id: "weapon.common.simple-knife",
        populatorType: "item",
        name: ["Knife", "Simple Knife", "Rusty Knife"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 5, max: 15 } },
    },
    {
        id: "weapon.common.simple-dagger",
        populatorType: "item",
        name: ["Dagger", "Simple Dagger", "Rusty Dagger"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "dagger", damage: { min: 5, max: 20 } },
    },
    {
        id: "weapon.common.simple-bow",
        populatorType: "item",
        name: ["Bow", "Simple Bow", "Lame Bow"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 5, max: 20 } },
    },
    {
        id: "weapon.rare.nice-bow",
        populatorType: "item",
        name: ["Nice Bow", "Nice Longbow"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 20, max: 50 } },
    },
    {
        id: "weapon.common.simple-crossbow",
        populatorType: "item",
        name: ["Crossbow", "Simple Crossbow", "Lame Crossbow"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "crossbow", damage: { min: 5, max: 30 } },
    },
    {
        id: "weapon.rare.nice-crossbow",
        populatorType: "item",
        name: ["Nice Crossbow", "Nice Heavy Crossbow"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "crossbow", damage: { min: 30, max: 70 } },
    },
    {
        id: "weapon.common.simple-staff",
        populatorType: "item",
        name: ["Staff", "Simple Staff", "Lame Staff"],
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "bow", damage: { min: 5, max: 30 } },
    },
    {
        id: "weapon.rare.nice-staff",
        populatorType: "item",
        name: ["Nice Staff", "Nice Heavy Staff"],
        tier: "rare",
        type: "weapon",
        weapon: { weaponType: "staff", damage: { min: 30, max: 70 } },
    },
    {
        id: "weapon.animal.wolf-paws",
        populatorType: "item",
        name: "Wolf Paws",
        tier: "common",
        type: "weapon",
        weapon: { weaponType: "knife", damage: { min: 10, max: 15 } },
        lootable: false,
    },
] as Array<INodePopulator>;
